import type { LucideIcon } from "lucide-react";
import {
  Award,
  BadgeCheck,
  BookOpen,
  Bot,
  Brain,
  Briefcase,
  Building2,
  Calculator,
  CalendarDays,
  ChartColumn,
  ChartLine,
  Clapperboard,
  Cpu,
  Earth,
  FilePen,
  FileSearch,
  FileSpreadsheet,
  FileText,
  HeartHandshake,
  Images,
  Layers,
  Lightbulb,
  Lock,
  Mail,
  MapPin,
  MessageCircle,
  MicVocal,
  MonitorSmartphone,
  Newspaper,
  Palette,
  PenTool,
  QrCode,
  ScrollText,
  Search,
  Share2,
  ShieldCheck,
  ShoppingCart,
  Sparkles,
  Sprout,
  Star,
  Target,
  Timer,
  TrendingUp,
  Trophy,
  Tv,
  Users,
  WandSparkles,
  Wrench,
} from "lucide-react";

/* String key → icon component, for DB-stored menu items. Keys must stay in
   sync with ICON_KEYS in lib/menu.ts (the admin picker's source of truth). */
export const NAV_ICONS: Record<string, LucideIcon> = {
  award: Award,
  badgeCheck: BadgeCheck,
  bookOpen: BookOpen,
  bot: Bot,
  brain: Brain,
  briefcase: Briefcase,
  building2: Building2,
  calculator: Calculator,
  calendarDays: CalendarDays,
  chartColumn: ChartColumn,
  chartLine: ChartLine,
  clapperboard: Clapperboard,
  cpu: Cpu,
  earth: Earth,
  filePen: FilePen,
  fileSearch: FileSearch,
  fileSpreadsheet: FileSpreadsheet,
  fileText: FileText,
  heartHandshake: HeartHandshake,
  images: Images,
  layers: Layers,
  lightbulb: Lightbulb,
  lock: Lock,
  mail: Mail,
  mapPin: MapPin,
  messageCircle: MessageCircle,
  micVocal: MicVocal,
  monitorSmartphone: MonitorSmartphone,
  newspaper: Newspaper,
  palette: Palette,
  penTool: PenTool,
  qrCode: QrCode,
  scrollText: ScrollText,
  search: Search,
  share2: Share2,
  shieldCheck: ShieldCheck,
  shoppingCart: ShoppingCart,
  sparkles: Sparkles,
  sprout: Sprout,
  star: Star,
  target: Target,
  timer: Timer,
  trendingUp: TrendingUp,
  trophy: Trophy,
  tv: Tv,
  users: Users,
  wandSparkles: WandSparkles,
  wrench: Wrench,
};

export const navIcon = (key?: string | null): LucideIcon =>
  (key && NAV_ICONS[key]) || Sparkles;
